FROM mcr.microsoft.com/dotnet/core/sdk:6.0 AS build
WORKDIR /app

# Copiar o projeto e restaurar as dependências
COPY . .

RUN dotnet restore
RUN dotnet publish -c Release -o out

# Construir a imagem de produção
FROM mcr.microsoft.com/dotnet/core/aspnet:6.0
WORKDIR /app
COPY --from=build /app/out .

# Expõe a porta em que a aplicação estará escutando
EXPOSE 80

# Comando para iniciar a aplicação quando o contêiner for executado
ENTRYPOINT ["dotnet", "FazAcontecerAPI.dll"]
